+-- ----------------------------
+-- Table structure for fake_pcs
+-- ----------------------------
+DROP TABLE IF EXISTS `fake_pcs`;
+CREATE TABLE `fake_pcs` (
+  `npc_id` int(11) NOT NULL,
+  `race` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `sex` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `class` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `title` varchar(16) NOT NULL DEFAULT '',
+  `title_color` char(6) NOT NULL DEFAULT 'FFFFFF',
+  `name` varchar(35) NOT NULL,
+  `name_color` char(6) NOT NULL DEFAULT 'FFFFFF',
+  `hair_style` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `hair_color` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `face` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `mount` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `team` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `hero` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `pd_under` int(11) NOT NULL DEFAULT '0',
+  `pd_under_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_head` int(11) NOT NULL DEFAULT '0',
+  `pd_head_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_rhand` int(11) NOT NULL DEFAULT '0',
+  `pd_rhand_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_lhand` int(11) NOT NULL DEFAULT '0',
+  `pd_lhand_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_lrhand` int(11) NOT NULL DEFAULT '0',
+  `pd_lrhand_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_gloves` int(11) NOT NULL DEFAULT '0',
+  `pd_gloves_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_chest` int(11) NOT NULL DEFAULT '0',
+  `pd_chest_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_legs` int(11) NOT NULL DEFAULT '0',
+  `pd_legs_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_feet` int(11) NOT NULL DEFAULT '0',
+  `pd_feet_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_back` int(11) NOT NULL DEFAULT '0',
+  `pd_back_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_hair` int(11) NOT NULL DEFAULT '0',
+  `pd_hair_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_hair2` int(11) NOT NULL DEFAULT '0',
+  `pd_hair2_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_rbracelet` int(11) NOT NULL DEFAULT '0',
+  `pd_rbracelet_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_lbracelet` int(11) NOT NULL DEFAULT '0',
+  `pd_lbracelet_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_deco1` int(11) NOT NULL DEFAULT '0',
+  `pd_deco1_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_deco2` int(11) NOT NULL DEFAULT '0',
+  `pd_deco2_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_deco3` int(11) NOT NULL DEFAULT '0',
+  `pd_deco3_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_deco4` int(11) NOT NULL DEFAULT '0',
+  `pd_deco4_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_deco5` int(11) NOT NULL DEFAULT '0',
+  `pd_deco5_aug` int(11) NOT NULL DEFAULT '0',
+  `pd_deco6` int(11) NOT NULL DEFAULT '0',
+  `pd_deco6_aug` int(11) NOT NULL DEFAULT '0',
+  `enchant_effect` int(11) NOT NULL DEFAULT '0',
+  `pvp_flag` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `karma` int(10) unsigned NOT NULL DEFAULT '0',
+  `fishing` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `fishing_x` mediumint(9) NOT NULL DEFAULT '0',
+  `fishing_y` mediumint(9) NOT NULL DEFAULT '0',
+  `fishing_z` mediumint(9) NOT NULL DEFAULT '0',
+  `invisible` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  PRIMARY KEY (`npc_id`)
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
+
+-- ----------------------------
+-- Records
+-- ----------------------------
+INSERT INTO `fake_pcs` VALUES ('20544', '0', '0', '0', '', 'ffffff', 'Elder Keltir', 'ffffff', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '6580', '0', '0', '0', '5771', '0', '0', '0', '374', '0', '0', '0', '5783', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');